apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 3  # Runs 3 instances of your app
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: nadeeshamedagama/my-react-app:1.0  # Use your pushed image
          ports:
            - containerPort: 80

